# File: docker-compose.yml (Đặt ở thư mục gốc)
version: "3.8"

networks:
  mactwo-net:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
  kafka_data:

services:
  # --- CÁC DỊCH VỤ HẠ TẦNG ---
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: mactwo_zookeeper
    networks:
      - mactwo-net
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: mactwo_kafka
    networks:
      - mactwo-net
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    volumes:
      - kafka_data:/var/lib/kafka/data
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  mysql:
    image: mysql:8.0
    container_name: mactwo_mysql
    networks:
      - mactwo-net
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mactwo_command_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: mactwo_redis
    networks:
      - mactwo-net
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5

  # --- DỊCH VỤ ỨNG DỤNG ---
  mactwo-command-service:
    container_name: mactwo-command-service
    # build: Chỉ dẫn cho Docker Compose tự build image từ mã nguồn
    build:
      context: . # Thư mục gốc chứa cả 2 project
      dockerfile: mactwo-command-service/Dockerfile # Đường dẫn đến Dockerfile
    ports:
      - "8081:8081"
    networks:
      - mactwo-net
    environment:
      # Cấu hình để kết nối tới các dịch vụ khác bằng tên container
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/mactwo_command_db?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=1
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS=kafka:9092
      # Các biến môi trường khác
      - SERVER_SERVLET_CONTEXT_PATH=/api/v1
      - APPLICATION_SECURITY_JWT_SECRET_KEY=aVeryLongAndSecureSecretKeyForMactwoEcommerceApplicationThatIsAtLeast256Bits
      - APPLICATION_SECURITY_JWT_EXPIRATION=86400000
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_started
